### ISSUE TITLE
Support for Xiaomi Mijia Pure Pro

### ISSUE THREAD

**Issue by vovkaprigarin** [merdok/homebridge-miot#142]
Can you add support for Xiaomi Mijia Pure Pro, please?

Thank you!

**Comment by merdok** [comment]
Hi,
I can do that, but it will take a while since i am currently working on rebuilding the plugin to allow better and faster integration of unsupported devices. Maybe in the meantime you can use another model as a device which is similar to yours and is already implemented. But you would need to provide me your **device mode**l so i can check which devices are similar to yours.

**Comment by vovkaprigarin** [comment]
Hi!

Probably like this leshow.humidifier.jsq1

**Comment by merdok** [comment]
Ok, you can try one of the currently supported humidifiers if any of them will work with yours.

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
