### ISSUE TITLE
New device support request zhimi.airpurifier.m1

### ISSUE THREAD

**Issue by wojciej** [merdok/homebridge-miot#147]
Hello,
Can I kindly request a support for Air Purifier 2 (mini) zhimi.airpurifier.m1.

Please let me know if you would need more details.
Thanks

**Comment by merdok** [comment]
Hi,
that should be no problem, but like already mentioned in the other issue since i am currently preparing a bigger update, it will take me some time to implementet that (probably no sooner then january).

But since the device is has exactly the same spec as **zhimi.airpurifier.ma2**, you can as a temporary workaround just simply put **zhimi.airpurifier.ma2** as model in your config and it should work!

**Comment by merdok** [comment]
Someone already submitted support for the device in #156, you can either manually already download the added files or wait for the next update.

**Comment by wojciej** [comment]
hey @merdok thank you for your reply and the follow up.
That is a good news.
Good luck with the bigger update. Will be happy to use it once released.

Thanks
