### ISSUE TITLE
Support for yeelink.light.mono6

### ISSUE THREAD

**Issue by edzdamangere** [merdok/homebridge-miot#153]
Can we please get support for the yeelink.light.mono6. I see that the mono4 is supported.

**Comment by merdok** [comment]
Sure, that should be possible! But it will take quite some time since I am working on rebuilding the plugin right now and that might take some time.

**Comment by fran-at** [comment]
I support this open issue. I am having some troubles, it is detected as a switch and cannot be dimmed the light intensity.
Thanks so much for your work @merdok !

**Comment by merdok** [comment]
It cannot be dimmed since it is detected as a generic accessory instead of a light accessory. Proper device class is needed to make it work correctly. 
I will not be able to add proper support in the next couple weeks or months since my code base locally is a big construction site due to the rebuild. 
I can only say that you could try to add proper support by yourself by submitting a pull request. It is quite easy to do it and you could have a look at some closed pull requests to get an idea what is needed.

**Comment by merdok** [comment]
Hi guys, can any of you tell me what is the actual name of the device? Like post a link to product page? Not sure exactly how i should name it 😅

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
