### ISSUE TITLE
new device support request deerma.humidifier.jsq / deerma.humidifier.mjjsq /

### ISSUE THREAD

**Issue by hAMMERlized** [merdok/homebridge-miot#154]
Hey man,

I love your plugin it works like a charm so far. Thanks for that. I've already red that you are working on a major update in january but after this could you implement support for the Xiaomi / Mija Humidifiers stated above? 

If needed, the correct Model Numbers are "MJJSQ03DY" (the.mjjsq Version) and "ZNJSQ01DEM" (the.jsq Version).

Any chance I can use them already with your plugin until it'll be (hopefully) implemented someday?

Thanks in advance.

**Comment by merdok** [comment]
Hi,
yes, i can do that but as you already mentioned it will take a while, since i plan to improve the plugin quite a lot and this takes more time then i thought. I marked this as a new device support and will come back to it as soon as the next major update is released. For now you can try to use the `deerma.humidifier.jsq4` as model, it is quite similar to the ones you got so it might work.

**Comment by hAMMERlized** [comment]
Thanks for the quick response. I'll give it a shot. Keep up the good work!

**Comment by hAMMERlized** [comment]
Hey @merdok ,

unfortunately _deerma.humidifier.jsq4_ is not working. Temperatur, Humidity as well as the Switches fan and display don't work. Any other device model I could try?

Thanks

**Comment by merdok** [comment]
There is one more which you can test i think, just check in the supported devices file for the model

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
