### ISSUE TITLE
Request: Aqara Protocol Support

### ISSUE THREAD

**Issue by mrking** [merdok/homebridge-miot#157]
Some newer Aqara devices won't be receiving support in the Mi Home app (confirmed by Aqara Support). Normally this has been ok because Aqara devices are HomeKit enabled. However, there are a few exceptions such as the AC Partner devices attached to the recently released G3 Camera not receiving HomeKit support. Would like to see support added for Aqara Protocol which is fairly similar to the MIIO protocol since XiaoMi owns the company.

**Comment by mrking** [comment]
If there's no objection to adding Aqara protocol support, I'm happy to have a go adding it.

**Comment by merdok** [comment]
Hi, generally i have no objection, but i would like to understand how the aqara protocol works and how much additionally complexity it brings into the plugin. Does it also base on the miot specs? 
Also please keep in mind that i currently work on a complete rebuild of the plugin. You can definitely already prepare a pull request but i would suggest that we merge it no sooner then after the next big update (i hope i can finish that by January/February) since it might introduce quite some conflicts (depending on how much adjustments are needed for the aqara protocol).
