### ISSUE TITLE
Support for zhimi.humidifier.ca1

### ISSUE THREAD

**Issue by OlehProkopenko** [merdok/homebridge-miot#164]
It's almost identical to ca4 but an older model so hope it won't be an issue.

**Comment by merdok** [comment]
Hi,
it should be no problem, but since i am right now working on a bigger update which takes longer then expected, i will probably be able to add that device no sooner then in February. 
In the meantime i can encourage you to submit a pull request with support for that device, adding it should be straight forward and helps me to focus on the big update.

**Comment by merdok** [comment]
Support is now added in version 1.0.0!
