### ISSUE TITLE
Issue: mi Smart plug failed auth 

### ISSUE THREAD

**Issue by Vannixxo** [merdok/homebridge-miot#168]
Mi two smart plugs always worked fine (Mi Cloud), starting from today homebridge console reports: 401 unauthorized, and the devices can’t be controlled

**Comment by merdok** [comment]
Maybe something changed with your account? A 401 in general means that you do not have access to the service/account.

**Comment by Vannixxo** [comment]
Nope, same credentials. App works regularly!

**Comment by merdok** [comment]
It does not matter if your app works or not, something might have changed with your account which now prevents access to some services (i guess maybe there was some kind of switch between years in your country regarding regarding your account?)

**Comment by iishrnika** [comment]
Hey, I have the same issue with all of my xiaomi devices.

**Comment by merdok** [comment]
What country do you have your devices on and what country is your micloud account setup for? Also could you post a homerbidge debug log,deally with the the `deepDebug` parameter set to `true `, so at least i can have a look at what point it fails for you.
My suspicion is that either Xiaomi changed something or something with your account changed (might be specific for your country since for me all devices over micloud are working fine)

**Comment by iishrnika** [comment]
Hey, my xiaomi devices are in romania, but the only server that worked previously was DE, so it's set on Germany. How can i export my log file, or it's ok to post it here with copy paste?

**Comment by merdok** [comment]
Interesting... I am not aware of any changes to micloud for the Germany region. 

Please no copy/paste as it might get too big 😄  Try to attach it as a .txt file or post it on gist https://gist.github.com/ just make sure to remove any sensitive information.

**Comment by iishrnika** [comment]
https://gist.github.com/iishrnika/1c57c643e7813955fc6e693c489a97e8

**Comment by iishrnika** [comment]
If i did it wrong please say.

**Comment by merdok** [comment]
That does not help me much. Like i already mentioned above you need to run homebridge in debug mode and additionally enable the `deepDebugLog`  parameter for one of your devices which has this issue.

**Comment by iishrnika** [comment]
hey, i just updated it with the deepDebugLog on

**Comment by kovapatrik** [comment]
I don't know if it matters much, but I have the same issues and my account is also in Germany region.

**Comment by merdok** [comment]
Well not sure what the issue here is, might be that something changed with the germany server (but why only Germany?) or it might be just a temporary issue due to a bug...
I think for now you need to observe that for a couple of days and see if it will start work again... other then that, you can try to move your devices to another server (i have all my devices on the CN server and they are working fine)

**Comment by iishrnika** [comment]
Thanks.

**Comment by kovapatrik** [comment]
Okay, thanks for the help!

**Comment by zormic** [comment]
Have the same problem with mine...

**Comment by merdok** [comment]
@zormic also got your devices on the Germany server?

**Comment by zormic** [comment]
Yup!

**Comment by Vannixxo** [comment]
Yes Germany server (one device requires it)

**Comment by Seger85** [comment]
We had a worldwide server failure on December 31st. since then all servers are online, only the DE server is still causing problems, the devices are not listed on the server and you can only log in to a limited extent. Do you always have to rely on the server? Thought with the token it runs locally. However, like you, I am currently not getting the token. I think we have to wait or move to another server, which I don't want.

**Comment by merdok** [comment]
@Seger85 as i thought, there must have been something going on with the server...
Yes, for device which does not support the miot protocol natively (older devices, which was released before around 2020) all commands has to go over the micloud, which takes care of the translation of the older protocol to the miot protocol. On newer devices all commands are sent locally and a micloud connection is not needed. 

Like i already mentioned the best would be first to wait a couple of days and see if xiaomi fixes the issue (maybe due to holidays in Germany nobody could have a look at the issue yet). 
Another option would be to switch to another server since all other servers seems to work fine.

**Comment by Seger85** [comment]
Hey @merdok,

you had just said that it is only for devices before about 2020 so how exactly do you find out and do you happen to know how it behaves with the device:

xiaomi air purifier 3c

The release year is not that long ago:
Late 2020/early 2021

Thank you for all and fingers crossed that the DE servers are back soon ;-)

**Comment by merdok** [comment]
@Seger85 air purifier 3c is a native miot device, you do not need micloud to control it, should also work with local commands.

**Comment by Seger85** [comment]
@merdok 
I don't know how it should work locally, the token must be entered in your plugin.

My token was reset somehow, so I have to get the current one.
 
My device was offline so I had to reset the wi-fi settings and it hasn't shown up in Homebridge since. It looks like my air purifier 3C got a new token.

Maybe you would be so kind and explain it to me here or by email.

Thank you very much,
Seger

**Comment by merdok** [comment]
@Seger85 this is not the correct place to discuss your token changes since it has nothing to do with the issue. 
If your token changed, then you have to get a new one and enter it in the config.json

**Comment by Seger85** [comment]
Hey buddy,

I'll try an e-mail, but I don't know if it'll get through. I don't know where else to ask for what I need ;).

My problem lies exactly in your description. I can only get a new token via this tool, which requests the server, right? Or do I have a possibility to get the new token locally? If so, then of course I have understood it and it would be my desired local solution.

Thank you very much,
Seger

Von meinem iPhone gesendet

Am 03.01.2022 um 07:53 schrieb Marcin ***@***.***>:

﻿
@Seger85 this is not the correct place to discuss your token changes since it has nothing to do with the issue.
If your token changed, then you have to get a new one and enter it in the config.json

**Comment by merdok** [comment]
Please use the README for that, there is a dedicated page which gives a couple of options on how to get the token here: https://github.com/merdok/homebridge-miot/blob/main/obtain_token.md

**Comment by kikiwora** [comment]
Yeah, I have the same issue. The DE server is used and nothing works as a result - 401 authorization failure :(
And the funny thing here is that Xiaomi disabled LAN control for lots of devices (at least Yeelight devices), so now we have no choice but to use cloud (which doesn't work at this moment)

**Comment by merdok** [comment]
Ok got an update. It seems that Xiaomi changed the authentication on the DE server to a more secure one, but all other servers are still using the older one. I do not know why they did this only on the DE server.
Anyway, it seems that i will have to look at the MiCloud protocol code and update it with the authentication which is used on the DE server. I will be looking into that in the next days and hoping to get a fix as soon as possible!

**Comment by zormic** [comment]
It appears to be working since this morning!

**Comment by merdok** [comment]
I think they have some issues right now with their servers. I often see that my devices cannot sync even on china servers.

**Comment by merdok** [comment]
Hmm, seems like the Germany server is working again by using the old authentication. Can you guys confirm that the issue is fixed for you?

**Comment by kikiwora** [comment]
> Can you guys confirm that the issue is fixed for you?

Yep, all seems to work just fine from this morning.

**Comment by Seger85** [comment]
+1

**Comment by iishrnika** [comment]
+2


Sent from Yahoo Mail for iPhone


On Tuesday, January 4, 2022, 5:17 PM, Seger85 ***@***.***> wrote:




+1

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by merdok** [comment]
Ok, so it was indeed in the end just some kind of a bug with the DE server which caused the old authentication not to work anymore and they seem to fixed it. Good to hear 👍 

I already did implement the new authentication thou (the same as the mi home app uses), and will be switching to that in a future update (**no action will be needed from you**), but at least i do not have to rush now and properly test everything!
