### ISSUE TITLE
Heater LED no Working as expected 

### ISSUE THREAD

**Issue by firewhank** [merdok/homebridge-miot#257]
Hi,
In one of the latest updates, I noticed that the LED control on the HomeKit is not working 100%

When it at 0% it turn on the screen a full brightness and at 1% turns off.

I can’t set the slider in any other position. It automatically goes to 1% when try something highest

**Comment by firewhank** [comment]
Smartmi heater

**Comment by merdok** [comment]
Hi, you need to provide me with the specific heater model so I can have a look.

**Comment by firewhank** [comment]
Hi
Smartmi Smart Convector Heater 1S

**Comment by merdok** [comment]
Thanks, will check it out!

**Comment by merdok** [comment]
Should be fixed in version 1.1.0.
The full value range will not be used, since there are 3 possible values the ranges are: 0-33, 34-66 and 67-100. The slider will automatically adjust to the nearest value.
Please note that the device has some strange way to set the values :
0 - full brightness
1 - middle
2 - off
not sure why they decided to do it that way, but this unfortunately will reverse the slider, meaning:
0% -full brightness
100%(67%) - off
