### ISSUE TITLE
Gateway devices, camera support

### ISSUE THREAD

**Issue by Semir333** [merdok/homebridge-miot#274]
**Xiaomi Mi Smart Home Hub V3**

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
The hub controll Zigbee devices (eg. Zigbee Xiaomi Wall Plug), a BT Gateway. Also can be control Secure function to alarm when door sensor contact open etc. The gateway have 4 alarm modes ( away from home, at-home, sleep and off). The MIOT plugin support, but the lumi.gateway.mgl03 is show chinese sings, two swtich not doing anything, and to for the leds.

**Xiaomi Smart Plug (Zigbee)**

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
This device not have IP and token. Controlled via Zigbee, and applyed from gateway. This device not shown in the MIOT Plugin.

**Xiaomi Mi Home 360 Camera and Xiaomi IMI EC2,EC3 outdoor camera**

**Does the device require a MiCloud connection?**
Yes

**Anything special about the device?**
Indoor and outdoor cameras. Homekit compatibility for not only turn on and off, i think it's a good point to support Homekit camera plugin, to show the videos also. The chuangmi.camera.025b02  and  chuangmi.camera.ipc019  (this one not support led function, others yes)  and   chuangmi.camera.029a02   and both not support the video showing.

**Comment by mtnmx** [comment]
Hello, Mi Smart Home Hub (v3) Chinese model ZNDMWG03LM, and the global version model ZNDMWG02LM are HomeKit devices compatible, so... I wonder why to add this hub in Homebridge?

**Comment by merdok** [comment]
The gateway will only allow you to control the alarm or light (if available) and not the devices via the miot protocol. You can already your gateway right now, please have a look here on how to do it: https://github.com/merdok/homebridge-miot/issues/258

Zigbee devices cannot be controlled using this plugin so the Xiaomi Smart Plug will not work.

And cameras unfortunately are very hard to do and i would first need an actual camera in order to even be able to add that functionality. Since i currently do not have such camera i cannot do it...
