### ISSUE TITLE
Roborock S5 rooms and filter detection

### ISSUE THREAD

**Issue by misanthrophy** [merdok/homebridge-miot#289]
**Describe the idea or improvement**
I previously used the plugin: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum which has more features for the roborock like rooms and status of filters.

**Describe the solution you'd like**
Is there a chance to port the features from the other plugin to yours, so that I am still be able to use different rooms in scenes/automations etc. And the status of filters is also handy to know, when you have to replace them. Maybe with the customAccessory section? 

**Additional context**
If you need any additional information on how this is exposed via the plugin just let me know how to debug this for you. 

Thx in advance for the great plugin!

EDIT:
I just read through https://github.com/merdok/homebridge-miot/blob/main/docs/robotcleaner.md but unfortunately there is no section for roborocks. Are they different than those described there? The only way I was able to get my rooms "detcted" was with that method: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#semi-automatic

**Comment by merdok** [comment]
If your device supports filter status then it will be shown. The futures of this plugin are dependent of what your device actually supports.
Unfortunately the robotics s5 which you have is an old device which does not support the miot protocol natively. In order to make it work the miot protocol is emulated on the MiCloud by xiaomi (hence the MiCloud requirement for your device), but for some reason xiaomi decided to reduce the features during that emulation and that includes the filter status which might have been available in the old miio protocol. The same unfortunately goes for room cleaning which is missing in the miot protocol for your device.
This is not under my control and I cannot change that..:
