### ISSUE TITLE
Please add support for Yeelight Smart Bathroom Heater

### ISSUE THREAD

**Issue by z-x-f** [merdok/homebridge-miot#322]
**Device model**
yeelink.bhf_light.v2

**Device name**
Yeelight Smart Bathroom Heater

**Does the device require a MiCloud connection?**
No

Thanks!

**Comment by merdok** [comment]
Should not be a problem! Will add full support for it in the next update! You can already add it now and try to use it if not yet tried as it should be automatically be detected.

**Comment by merdok** [comment]
Ok, might be the light-extension property...

**Comment by merdok** [comment]
The device is now added in version 1.3.0

**Comment by z-x-f** [comment]
After upgrading to 1.3.0, I tested it, and it seems that I need to select force micloud connection before I can control the device. Can the device be controlled only through LAN without using cloud? In HA, I tested https://github.com/al-one/hass-miio-yeelink, https://github.com/al-one/hass-xiaomi-miot can control this device via LAN.

**Comment by merdok** [comment]
You specified in your request that the device does not require a micloud connection.

Your device cannot be controlled locally using the miot protocol because it natively does not support it. For this reason a micloud connection is required for this plugin, since micloud emulates the old commands to the new miot ones.

**Comment by z-x-f** [comment]
Ah, Sorry, I didn't understand the situation clearly. Before I specified that micloud was not needed because the previous test in ha could be controlled through LAN, so I thought that this plugin could also control this device through LAN:)

**Comment by merdok** [comment]
You should always first try to add a device in the plugin, even when it is not supported. The plugin will automatically try to identify and set it up. If that fails you can do another try with forceMiCloud and if that works it will be an indication whether micloud is required or not. I cannot unfortunately do that myself since I do not have most of the devices.

This plugin only supports the new miot protocol. Older devices still work but require a micloud connection.

**Comment by z-x-f** [comment]
I see, this device is using the old miot protocol and needs micloud to emulate the new miot protocol, right?
