### ISSUE TITLE
Please add support for Roborock S6

### ISSUE THREAD

**Issue by adrenalini** [merdok/homebridge-miot#341]
**Device model**
oborock.vacuum.s6 (https://home.miot-spec.com/spec/roborock.vacuum.s6)

**Device name**
Roborock S6

**Does the device require a MiCloud connection?**
Do not know

**Anything special about the device?**
The device is detected by the plugin, however does not react to any actions (e.g. won't start once turned on via HomeBridge / Apple Home). Also shows battery as empty and not charging even though the device is online and docked.

**Comment by merdok** [comment]
I am pretty certain the S6 requires a Micloud connection. You need to add the `micloud` section to your config, add your credentials and set the `forceMiCloud` property to `true`.

**Comment by adrenalini** [comment]
Unfortunately adding Micloud credentials does not help - account requires 2FA and I end up in a prompt to use the link (which btw does not help when trying to use “Discover all devices using Micloud” option, seems to be a known issue with other tools that get tokens).
![456ACC40-0EF5-42A0-BDDB-D3FEEB095E74](https://user-images.githubusercontent.com/114061994/191570602-200742e8-7ccf-49ec-87eb-dc0bb94391f4.jpeg)

Also, a dedicated plugin I previously used did not require Micloud.

**Comment by merdok** [comment]
A dedicated plugin which you previously used also did not use the miot protocol but the old miio one which is outdated right now. Your device is unfortunately using the old miio protocol, so in order to be able to control micloud is required since it has a translation layer which translates miot commands into miio.

You would need to disable 2FA then.
