### ISSUE TITLE
Help! I want to modify mode buttons on my fan

### ISSUE THREAD

**Issue by pb29** [merdok/homebridge-miot#349]
my circulator got four modes.  direct, natural, smart, sleep.
And if i able mode buttons on plugin settings via homebridge ui x, it displays four switches on homekit. 
i want to make it displays only natural mode switch and it should be toggle switch between only direct and natural. How can i manage to change these?

**Comment by merdok** [comment]
Hi, 
a similar issue has already been discussed here: https://github.com/merdok/homebridge-miot/issues/337
This is not possible directly currently since a switch can only display two states, what would you do with the intermediate states?
Nevertheless, you can at least reduce the numer of switches to only those which you really need. Have a look a `propertyControl` to accomplish that.
