### ISSUE TITLE
MiCloud 2h Air purifier 

### ISSUE THREAD

**Issue by adamrzanek** [merdok/homebridge-miot#36]
I’ve noticed that Air purifier 2h add my micloud account doesn’t have fan control at all :)
![3042B11E-C0E2-4547-9FF7-D7A353F187B6](https://user-images.githubusercontent.com/65444919/120379664-6113f600-c320-11eb-945c-511f98011502.jpeg)
![B4FFEF6F-626F-4B86-A9AD-F64D34ED13D9](https://user-images.githubusercontent.com/65444919/120379668-62ddb980-c320-11eb-8c5c-94379daa0ae7.jpeg)

**Comment by merdok** [comment]
The Air Purifier 2H has no steeples fan control, at least in the miot protocol which is used here:
http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mc2:1

**Comment by adamrzanek** [comment]
Ok, thanks :)

**Comment by dbartelmus** [comment]
Im using the same Air Purifier, it seems that fan speed control of 2H model is achievable via official Xiaomi app and also by using attributes, so I think it lacks of implementation in particular model presets:

Air Purifier 2S (zhimi.airpurifier.mc1) and 2H (zhimi.airpurifier.mc2)

Power (on, off)
Preset modes (auto, silent, favorite)
Buzzer (on, off)
Child lock (on, off)
LED (on, off)
Favorite Level (0...16)

Attributes:
model
temperature
humidity
aqi
mode
filter_hours_used
filter_life_remaining
favorite_level
child_lock
led
motor_speed
average_aqi
learn_mode
extra_features
turbo_mode_supported
button_pressed
filter_rfid_product_id
filter_rfid_tag
filter_type
illuminance
buzzer

**Comment by merdok** [comment]
Since this plugin is using the miot protocol for communication with the device, for older devices which use the cloud for emulation of the protocol, not all functionality will be available. I suspect that the official xiaomi app uses the old miio protocol to communicate with the device hence it is possible there.

As an example those particular devices here are simply missing the fan control in the miot spec hence it is not possible.
