### ISSUE TITLE
Add support for Dreame D9 / dreame.vacuum.p2009

### ISSUE THREAD

**Issue by eralilo** [merdok/homebridge-miot#37]
Hi,

any chance you could implement support for the Dreame D9 (dreame.vacuum.p2009) vacuum cleaner robot?
Current behavior on 0.9.2 is same as #24 - configured as fan switch, but switches off after 1-2 seconds. When the robot is actually running, the switch is on. There is also only one switch present in HomeKit.

Thanks! Filip

**Comment by merdok** [comment]
Yes, this should be straightforward :) I will add support for that vacuum in the next update. Will let you know when it is ready!

**Comment by eralilo** [comment]
Awesome, can’t wait for it 👍

**Comment by Lukas2504** [comment]
Perfect, thanks can't wait anymore ;)

**Comment by merdok** [comment]
Support for the vacuum cleaner is now added in version 0.9.3. Could you please try it out and let me know if it works?

**Comment by eralilo** [comment]
Works like a charm!
All switches are present and working as expected, thank you so much!!!

**Comment by majidmostafa** [comment]
Hi Guys,
Please I have an issue with my Dreame Vacuum D9 (dreame.vacuum.p2009) which is dead!! (No interaction, no light, no reaction, ...) before that I have switched my Mi Home account from Singapore to French ( because I wanted to link it with my Alexa :( )
It was fully charged and it have requested me to update the firmeware but after that I disovered that the robot is dead and I tried to reset it but no reaction. from that moment I can't do anything as it is fully Off and no signe of reactvitiy, is like the systeme has been erased or its Soft have been broken due to the firmeware update.
Can you please help me to resolve this issue?
For information, I installed the token extractor and I can see the Vaccum linked in my account Singapore and I can see also its token.
Many thanks for your help and support
