### ISSUE TITLE
Add Support for Mi Purifying Fan

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#372]
**Device model**
dreame.fan.p2018

**Device name**
Xiaomi Smart Purifying Fan

**Does the device require a MiCloud connection?**
No

**Anything special about the device?**
Does it already work with the plugin with a limited scope? - Yes
- this device is fan + air purifier hybrid. The plugin exposed this device as a fan which works great as it also expose the temperature sensor
- however, since it also doubles as an air purifier, I wish the plugin can expose its air quality sensor and filter life

![MiPurifyingFan-01_1000x jpg copy](https://user-images.githubusercontent.com/66505845/198887402-fdb8f4c1-6735-47ba-ae49-8c060dd2b3ae.jpg)

**Comment by merdok** [comment]
The device main type is a fan, so it will always be recognizes as that. If you wish to expose the additional data you can you use the `propertyControl`

**Comment by merdok** [comment]
Oh, yes sorry. You need to use `propertyMonitor` for that. Please see the example and documentation in the README, should be self explaining.

**Comment by merdok** [comment]
Well, propertyMonitor does not know what kind of property is behind there so it used the light sensor to display numeric values. Right now that is the best that be done. I might try to improve that in the future...

**Comment by merdok** [comment]
It is not about the fan device itself as that supports it in HomeKit. The thing is that there are various devices out there with many different combinations of features. Until you posted the bug here I was not even aware that there is a fan with a built in air purifier😅 So it is uncommon for fans to report Filter state.
With the robot vacuum it is a different story. Pretty much every vacuum reports that so that is added automatically.

As for the 2s fan, this is unfortunately impossible as the fan does not report the battery charging state.

For the other fan you would need to post a debug log to see why this is happening. Cannot tell without the log what the issues could be...

**Comment by merdok** [comment]
Thanks! I see the issue now, will be fixed in the next update!
