### ISSUE TITLE
Vacuum showing as a fan

### ISSUE THREAD

**Issue by franzmilec** [merdok/homebridge-miot#39]
Hi, I have both a vacuum and a fan by Xiaomi and they both show up as fans in HomeKit, which creates issues when controlling HomeKit with Siri. 

Would it be possible to differentiate the devices, ie. make all vacuums show up only as smart plugs?

**Comment by merdok** [comment]
Hi,

thanks for the feedback.
I actually also have the same setup as you (a vacuum and fan) and did not have any issues yet. I can understand that it might cause issues when you want to turn off all fans using Siri😅

- Anyway, I made the vacuum accessory as a fans since it is the closest to a vacuum which we currently have in HomeKit, also I was planning on using the fan slider to control additional things like the mode of the vacuum. Besides that having it configured as a fan you can faster distinguish which switch controls the actual vacuum and which one is for configuration in the group.

Your point is definitely valid but I am not sure how other people would think about it. It would be certainly possible to change it to a simple switch but that would close the door for me to implement extra functionality  using the rotation speed slider or rotation direction switch...

**Comment by franzmilec** [comment]
My Siri conversations go something like this:
- Hey Siri, turn off the fan.
- Which fan should I turn off? Fan, Vacuum, or both?
- Fan.
- Which fan should I turn off? Fan, Vacuum, or both?
- …

Anyways, I understand the issue – HomeKit is still a hot mess, and so is Siri. 😂

**Comment by merdok** [comment]
Maybe as a tip, try not to use the generic names for the devices. I call my fan "Smartmi Fan 3" and when I say to Siri to turn it on then it works without any questions asked😅 It is also to useful to say like "turn on the living room fan" if your fan and vacuum are in different rooms, that works well too.
