### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by adamrzanek** [merdok/homebridge-miot#4]
Hi, thanks for great work! 
1. Are you planning to implement Xiaomi 2H support? Is it possible?
2. I think Air Purifers should automaticly switch themself to manual mode when you control them by intensity silder. When you’re in automode nothing is happening when you’re doing this. 
3. Do you think you can implement Idle state for Air purifiers? Like in this plugin https://github.com/rgavril/homebridge-xiaomi-air-purifier3#readme ?
4. Do you think it is possible to make led/light accesorry to appear like this? 

![](https://user-images.githubusercontent.com/65444919/103709604-33b25e80-4fb3-11eb-9737-ddba79017024.png)

Jeszcze raz dzięki za super robotę!

**Comment by merdok** [comment]
Hello,

thanks for feedback, this is still relatively fresh and a work in progress so that helps me to improve the plugin. 

To you questions:
1. What exact device model has the Xiaomi Air Purifier 2H? If you can tell me that then implementing it should be straight forward 😄 
2. You are right and that makes a lot of sense, i will add it
3. What exactly does the "Idle" state mean? How do you know that the device is in idle state? I mean what the device does in idle state?
4. The led/light should already appear as a switch in the group, what is the difference to the picture above?

Dzięki 😃

**Comment by adamrzanek** [comment]
2H is zhimi.airpurifier.mc2 

Idle state is when The purifier fan is the lowest level when air quality is 1-7 I think. 

The light appears like a big switch rather then round button and whole air purifier panel is messed up

**Comment by merdok** [comment]
Are you sure that the zhimi.airpurifier.mc2 is a miot device? I think that this device still uses the old miio protocol...

I will look into implementing the idle state.

I do not think that it is possible to place additional switches on a device, from where do you have the screen capture above?

**Comment by adamrzanek** [comment]
I’m not sure that’s why I’m asking :) 
The screenshot is from 2h plugin I’m using

**Comment by merdok** [comment]
Which plugin do you use? I can have a look and tell you if this device is a miot device.

**Comment by adamrzanek** [comment]
https://www.npmjs.com/package/homebridge-mi-air-purifier This one

**Comment by merdok** [comment]
Unfortunately based on that link this device is a miio device which are not supported here.
