### ISSUE TITLE
Dreame D10 Plus Mode Issue

### ISSUE THREAD

**Issue by kimo790** [merdok/homebridge-miot#501]
I had a Dreame F9 and the docs helped me big time and the mode control was working with other property controls. I upgraded from few days to Dreame D10 Plus. the docs have also helped me again to get it started and working but the mode controls aren't anymore, my guess is that it already has a value in the selects array where it cannot be overwritten. 

I tried using the "2.3" action which has parameter "4" so i went to "2.4" in the properties tab and it asked for ROOMIDs with no parameter in or out, which confused me because i don't know what value to write in or how and therefore i 
wasn't able to execute this command/action.

could you please help me figure out a way maybe to command the vacuum to only clean a selected room with no other pre-set parameters so that maybe the mode control may work. Or maybe guide me to a way to listen to the communication protocols between the vacuum and the Mi home app

![2 3](https://github.com/merdok/homebridge-miot/assets/52041472/a47bde51-b17d-4eab-82b8-cd79c068c985)
![2 4](https://github.com/merdok/homebridge-miot/assets/52041472/4dddb7fe-7cea-471a-b964-edf85ff5b2cb)

**Comment by merdok** [comment]
Yeah, this part is always tricky. They sometimes change the way how parameter looks like, and besides knowing that it has to be string there is nothing else which we can learn from the miot spec. How the string should look like is always a discovery game, and the best way to find that out is to capture network traffic from the app. In the captured network traffic we were able to see how exactly the param would need to look like. 
The issue is, with newer devices the modified mi home app which was used to capture the command, does no work anymore and i am not sure if there is currently an alternative...
