### ISSUE TITLE
Poll failed 4 times in a row

### ISSUE THREAD

**Issue by terrorhai** [merdok/homebridge-miot#59]
Hey merdok,

me again ;)
I get the problem that after some days of homebridge running sometimes my Air Purifiers are not online anymore.
They are working without problems in the Mi Home App and are online in my network, but I need to restart homebridge to get it back to work. Is this problem related to this plugin?

[05/07/2021, 21:24:00] [miot] [Luftreiniger Wohnzimmer] Poll failed 4 times in a row! Stopping polling and trying to reconnect!

**Comment by merdok** [comment]
Hi,
you would need to provide a homebridge debug log ideally with the property deepDebugLog set to true. That way we will be able to see why the poll is failing and it will be simpler to find the root cause :)

**Comment by terrorhai** [comment]
Activated, will post it when the error occurs next time.

**Comment by dmndrz** [comment]
Same problem here.
I noticed it happens each time the internet network is interrupted or the router is rebooted.

**Comment by merdok** [comment]
@dmndrz would be nice if you could provide debug log also!

**Comment by Thijsjuh92** [comment]
I have the same issue, set deepdebuglog on true.

Where can i see this deepdebuglog?

**Comment by merdok** [comment]
You have to start homebridge in debug mode, that will show you the debug log.

**Comment by Thijsjuh92** [comment]
After updating local network, still works now past couple a days👌🏽

**Comment by Bene2103** [comment]
Hi,

i'll check in here cause i have the same problem. Heres the debug output from homebridge:
![1](https://user-images.githubusercontent.com/46553509/126981504-0fda6800-df39-4809-9787-53897db1f2a7.jpg)
![2](https://user-images.githubusercontent.com/46553509/126981514-d8e536c2-55ae-40d1-b22f-3c14f3db0f4a.jpg)
![3](https://user-images.githubusercontent.com/46553509/126981522-2834b69f-020f-455a-8b3b-025a53e0c636.jpg)
![4](https://user-images.githubusercontent.com/46553509/126981529-0b8fefac-f617-46e9-a23c-f87de08fdcb9.jpg)
![5](https://user-images.githubusercontent.com/46553509/126981536-546733d0-866d-4b01-968a-c37cdee57333.jpg)

And this is my config. Note that the pollinig interval is low so that i can produce logs without waiting so long.
![6](https://user-images.githubusercontent.com/46553509/126981596-44775511-8419-45f5-acb4-79389d1db7ad.jpg)

As you can see on the logs the plugin connects to the device at 13:21:15 and not even ten seconds later the device doesnt respond.

If you need any further information so let me know.

**Comment by merdok** [comment]
@Bene2103 this looks like a network issue to me. It might be that the device responds to slow so requests timeout. It also might be that your polling interval is set to high and the device is constantly asked with requests before it even can process the previous one. Default is 5 seconds. Try to increase to a higher value like 10 seconds or even 15 and check if that helps.

**Comment by Bene2103** [comment]
Thanks for your answer!

Ive searched the error code and text and found in the home assistant github that this seems to be a common issue
https://github.com/home-assistant/core/issues/36972

Maybe you can take a look at this PR this should fix the issue for them
https://github.com/home-assistant/core/pull/50755

Thank you!

**Comment by merdok** [comment]
@Bene2103 thanks for the link. I already have a mechanism to allow 4 fails since I know that this sometimes happens sporadically. It seems that in your case it happens quite often which indicates that it is an issue on your side. I would guess that it is either a network issue or the device gets to many requests and cannot process them on time, in that case I would recommend to increase the polling interval to reduce the load on the device.

**Comment by Bene2103** [comment]
With homebridge stopped and requesting the status via miiocli i also get the error code.

When im back home i will try restarting everthing and maybe resetting the purifier. 

Could it be possible that this plugin and miio conflict with my xiaomi vacuum plugin which also uses miio?
Even when their miio is bundled in the plugin?

I will try deactivating those maybe conflicting plugins and i will report back if i get any useful information.

**Comment by merdok** [comment]
The issue might be caused by to mucus load on the device, so if the other plugin also somehow polls the device then it could cause exactly the high load on the device which leads to the issue.

**Comment by Bene2103** [comment]
So i fixed my purifier.

I've noticed that the device wont even work within the Mi Home app. So i deleted the device in Mi Home and reset it via the buttons and reconfigured it.
After extracting the new token and configuring the plugin the device now works for about a week without problems.

Strange behaviour but now it works :-)

**Comment by merdok** [comment]
Sounds good, thanks for the info!
