### ISSUE TITLE
所有通过插件添加的空调全部无法用siri语音开启

### ISSUE THREAD

**Issue by 5iphoto** [merdok/homebridge-miot#603]
音箱只会咚咚，但是空调并不会开启

**Comment by merdok** [comment]
Could you please write your request in english?

**Comment by Viper488** [comment]
> Could you please write your request in english?
he said all the accontrol can't use by Siri ,I have the same issue too

**Comment by merdok** [comment]
Siri control is mostly about whether a device supports being controlled by Siri and how you named your switches.

**Comment by Viper488** [comment]
it seems like my ac partners aren't support. The HomeKit show me some button but do not work.

**Comment by merdok** [comment]
You need to check if your device requires a micloud connection. You can try to force the device to connect over the cloud.

**Comment by Viper488** [comment]
I am using mi cloud to connect my partner, but the HomeKit doesn't work

**Comment by merdok** [comment]
Then you would need to post some
Debug log so I can see what is going on

**Comment by Viper488** [comment]
Here is the part of homebridge log. Not only the ac parter, my other devices do not work
[homebridge.log.txt](https://github.com/user-attachments/files/16086908/homebridge.log.txt)

**Comment by merdok** [comment]
Based on the log which you provided i see the following error:
`[7/3/2024, 10:54:04 PM] [miot] [台灯] Poll failed 4 times in a row! Stopping polling and trying to reconnect! Reason: Error: Call to device timed out`
This error might indicate that the device does not support a local connection and you should try to use the micloud as already mentioned. You have set the `forceMiCloud` property to `true` for the devices which you want to force over cloud, otherwise they will continue to try with a local connection.
