### ISSUE TITLE
Request support for updating IP address dynamically for IoT devices

### ISSUE THREAD

**Issue by 7est** [merdok/homebridge-miot#649]
Due to certain special circumstances, I am unable to assign fixed IP addresses to my IoT devices. Their IP addresses may change from time to time, such as from 192.168.1.4 to 192.168.1.11. When this happens, my ability to control the devices and receive status updates becomes invalid.

Could you please let me know if there are any existing features I might have overlooked to address this issue?

Alternatively, I would like to request support for a feature that periodically requests device information updates from MiCloud to refresh the IP addresses.

Thank you for your assistance!

**Comment by merdok** [comment]
Hello,
thanks for the message. Unfortunately there is no feature currently which does what you requested. The ip address is fixed in the configuration and cannot be changed during runtime.

The usual scenario is that devices have assigned static ip addresses over the whole lifespan and it never changes. When a device ip periodically changes over the lifespan then it can have all kind of weird consequences which are hard to predict.

Currently I do not plan to provide such functionality as this would require some extensive just changes for a very rare edge case.

I can only recommended you to investigate the possibility to assign fixed ip address to your device. That option should be possible on pretty much every router.

**Comment by 7est** [comment]
Thank you for your prompt reply!

I’m wondering if forcing the use of MiCloud instead of Local requests in device settings could help mitigate this issue.
I’m not sure whether this approach would work effectively.

Do you have any suggestions or insights regarding this? Thank you again for your support!

**Comment by merdok** [comment]
As far as I remember correctly, when you have all the necessary info provided in the config and additionally set the forceMiCloud flag in the config, then the ip will not be used(although required in the config), a direct connection to the cloud will be made and all the data sync and actions will be executed over the cloud.

**Comment by 7est** [comment]
Thank you again for your detailed response!

If I’m not mistaken, I will keep this setting to avoid issues caused by changing IP addresses. I apologize for not having the permission to modify the router settings.
I will continue testing the forced use of MiCloud to see if it resolves the issue.

Thank you once again for your help!
