### ISSUE TITLE
fanLevelControl stays at 0 when adjusted

### ISSUE THREAD

**Issue by ahmadnazirafiq** [merdok/homebridge-miot#71]
I've been using one of your other plugin "homebridge-xiaomi-fan" which works great except that I can't stop/oscillate the fan in Control Center. But, I found out that this "homebridge-miot" can do that; a feature I sorely missed cause I often access devices through Control Center in iOS.

However, there's only one issue with it - it consistently reports zero speed when adjusting the fanLevelControl. Tried this on zhimi.fan.za4 (Smartmi Standing Fan 2S). My other Xiaomi fans like zhimi.fan.fb1 (Mi Smart Air Circulator Fan) and dmaker.fan.p9 (Mi Smart Tower Fan) doesn't exhibit this issue though.

Also, is it possible to change to other fan icon in HomeKit? I don't see that option, but my ceiling fan connected to wall switch does show three different fan icons.

![IMG_B2DA92C8B745-1](https://user-images.githubusercontent.com/66505845/128934554-be43436c-a220-4610-9504-992974ee505b.jpeg)

Appreciate your response. Thank you!

**Comment by merdok** [comment]
The zhimi.fan.za4 is not a miot device but i can use the miot protocol over the micloud to still allow controlling the device. The disadvantage with this approach is that this only supports a limited set of properties. For the zhimi.fan.za4 fan speed is not reported over micloud so that is why it shows as 0%.

As for the icon, icon changing is only supported on the old Fan v1 homekit accessory. This plugin uses the new Fan v2 homekit accessory which does not allow to change the icon. This is a limitation by Apple, why they removed the icon changing in the Fan v2 accessory i have no idea...

**Comment by ahmadnazirafiq** [comment]
Ah I see. Perhaps if its possible that the slider follows the fan speed we manually set?…  Just like we can with the AC partner v2. 🤷‍♂️

**Comment by merdok** [comment]
Normally it uses the fan level, but in that case it is kind of a special case which I first need to correctly handle! But I will check it put!

**Comment by ahmadnazirafiq** [comment]
I got excited too early when I saw the update 😅 only to find the speed still saying zero when adjusted haha

**Comment by merdok** [comment]
Well, sorry... did not have time to have a look it yet.

**Comment by ahmadnazirafiq** [comment]
Hi, any update on this? I’m guessing its not possible?

**Comment by merdok** [comment]
Issue should be fixed in version 0.9.17
