### ISSUE TITLE
Support for robot vacuum Mova L600 model dreame.vacuum.p2157

### ISSUE THREAD

**Issue by lukebelz** [merdok/homebridge-miot#80]
Hi,

Could you add support for the dreame.vacuum.p2157, sold as Mova L600. This is a very popular model as it has the highest suction power available in robot any vacuum and is only $250 on amazon right now.

Would be great if you could add support. Let me know if you need anymore information!

Thanks,
Luke

**Comment by lukebelz** [comment]
Just so anyone else knows, the using dreame.vacuum.p2029 as the id works enough to start and stop it through homekit, and I don't get any errors in homebridge.

Is there any way you could add room support? I have rooms set up in the Mi Home app, would be nice in homekit to tell it to clean certain rooms, as that's how I generally use it.

Also, it would be nice to be able to see the main and side brush life, as well as the filter life and battery charge. This app shows everything I want, but they don't support dreame based models and don't have plans to add them: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum

**Comment by merdok** [comment]
Sure, should be no problem to add proper support for that vacuum! Till i add full support you can use the workaround with the other model.

Room cleaning is already possible but not right now documented properly (need to finally do that...), you can check out this post on a small guide: https://github.com/merdok/homebridge-miot/pull/51#issue-681285371, just instead of `room_clean` for the action use `start_clean`.

Battery charge also is already there, just check the details of the fan accessory inside the group.
The same goes for filter life, it should also be already there!

As for main and side brush life, it is kind of hard to display that in the ui since there are not really any reasonable ui elements for that in homekit... the info is currently only displayed during homebridge startup in the log.

**Comment by merdok** [comment]
Support is now included in version 0.9.11
