### ISSUE TITLE
Air Purifier 2 (zhimi.airpurifier.mc2) has no fan speed control.

### ISSUE THREAD

**Issue by kikiwora** [merdok/homebridge-miot#96]
Hello there! 
The only issue with this device is the absence of fan speed control, the other plugin I've used before this one did have this feature, and it is highly desired.

Would you kindly fix this for the users of this device?

**Comment by merdok** [comment]
Hi, 
this is not an issue! The `zhimi.airpurifier.mc2` is an older device which uses the old miio protocol and not the new miot protocol. There is an emulation available to control the device using the miot protocol over the mi cloud but because of that some functionality is not available, that included the fan speed control. There is nothing that can be done with the miot protocol.
